<a href="https://colab.research.google.com/github/there-exist/thereexist_/blob/master/2019_11_28_Matrix_M_and_Qu_definition_by_using_matrix_calculation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np




def Qu(N):
    i = np.array([np.linspace(0,N,N+1)])
    k = i.T
    
    Qu = np.sqrt(2/(N+1))*np.cos(k*(i+0.5)*np.pi / (N+1))
    
    Qu = Qu.T
    
    Qu[:,0] = np.sqrt(1/(N+1))
       
    
    return Qu

    
    

In [0]:
print(Qu(3))

[[ 0.5         0.65328148  0.5         0.27059805]
 [ 0.5         0.27059805 -0.5        -0.65328148]
 [ 0.5        -0.27059805 -0.5         0.65328148]
 [ 0.5        -0.65328148  0.5        -0.27059805]]


In [0]:

def M(N):
    i = np.array([np.linspace(0,N,N+1)])
    k = i.T
    
    
    
    M = -4 * np.sin(k*np.pi / (2 * (N+1)))**2*np.identity(N+1)
    
    return M


In [0]:
print(M(3))

[[-0.         -0.         -0.         -0.        ]
 [-0.         -0.58578644 -0.         -0.        ]
 [-0.         -0.         -2.         -0.        ]
 [-0.         -0.         -0.         -3.41421356]]


In [0]:
def L(N):
    
    return np.round(np.dot(Qu(N), np.dot(M(N), Qu(N).T)),0)

In [0]:
print(L(6))

[[-1.  1. -0.  0.  0.  0. -0.]
 [ 1. -2.  1. -0. -0. -0.  0.]
 [-0.  1. -2.  1. -0. -0.  0.]
 [-0. -0.  1. -2.  1.  0. -0.]
 [ 0. -0. -0.  1. -2.  1.  0.]
 [ 0. -0. -0.  0.  1. -2.  1.]
 [-0.  0.  0. -0.  0.  1. -1.]]


In [0]:
print(np.kron(1,1))

1


In [0]:
def A(N):
    i = np.array([np.linspace(0,N,N+1)])
    k = i.T
    
    A = np.kron(i,k)
    
    return A

In [0]:
print(A(3))

[[0. 0. 0. 0.]
 [0. 1. 2. 3.]
 [0. 2. 4. 6.]
 [0. 3. 6. 9.]]
